services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shodhai-app:stable
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - PORT=8080
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=shodhAIpostgres
      - ML_URL=https://3m4szz0n9l.execute-api.ap-south-1.amazonaws.com/Prod
      - CLOUDINARY_CLOUD_NAME=damg6iidi
      - CLOUDINARY_CLOUD_API_KEY=554238382312718
      - CLOUDINARY_CLOUD_SECRET=WLS-smwAXQUupVHlI1q-15L0mCo
      - MAX_FILE_SIZE=20MB
      - MAX_REQUEST_SIZE=20MB
      - DDL_AUTO=update
      - SHOW_SQL=true
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shodhAIpostgres
      POSTGRES_DB: shodhai
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
